"""
CPO: Contrastive Preference Optimization
=========================================
Inspired by:
  - "Direct Preference Optimization: Your Language Model is Secretly a Reward Model"
    (Rafailov et al., NeurIPS 2023)
  - "Model-based Preference Optimization in Abstractive Summarization without
     Human Feedback" (Gao et al., EMNLP 2024)
  - "SLiC: Sequence-Level Contrastive Learning for Summarization"
    (Zhao et al., 2023)

Core idea: Instead of constructing hallucinated negative samples via heuristic
perturbation (which is brittle and domain-dependent), CPO uses the model's own
behavior as a signal. We construct "preference pairs" where:

  - "Preferred"  (y_w): reference summary — written by a human expert
  - "Dispreferred" (y_l): summary generated by the model *without encoder context*
    (i.e., decoder-only generation from BOS token). This represents what the
    model would produce if it ignored the source document — the "hallucination
    baseline".

We then apply a contrastive preference loss that pulls the model toward
preferred summaries and away from dispreferred ones, while maintaining
the standard cross-entropy objective.

Loss decomposition:
  L_total = L_ce + λ · L_cpo

Where L_cpo is a simplified DPO-style preference loss:
  L_cpo = -log σ(β · [log π_θ(y_w|x) - log π_θ(y_l|x)])

This is more principled than InfoNCE with heuristic perturbations because:
  1. Negatives come from the model itself (self-generated), not rules
  2. The DPO formulation directly optimizes for preference alignment
  3. No need for a separate reward model
"""

from typing import Dict, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


# ═══════════════════════════════════════════════════════════════════════
# Response projector: maps hidden states to a compact representation
# ═══════════════════════════════════════════════════════════════════════


class ResponseProjector(nn.Module):
    """Projects decoder hidden states to a compact representation for scoring."""

    def __init__(
        self,
        hidden_size: int = 1024,
        projection_dim: int = 128,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.projection = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.LayerNorm(hidden_size),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, projection_dim),
        )
        # Initialize with small weights
        nn.init.normal_(self.projection[0].weight, mean=0.0, std=0.01)
        nn.init.zeros_(self.projection[0].bias)
        nn.init.normal_(self.projection[4].weight, mean=0.0, std=0.01)
        nn.init.zeros_(self.projection[4].bias)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        # hidden_states: (B, T, D) → mean pool → (B, D) → project → (B, proj_dim)
        pooled = hidden_states.mean(dim=1)
        return F.normalize(self.projection(pooled), dim=-1)


# ═══════════════════════════════════════════════════════════════════════
# CPO Loss
# ═══════════════════════════════════════════════════════════════════════


class ContrastivePreferenceLoss(nn.Module):
    """Contrastive Preference Optimization loss for faithfulness.

    Constructs preference pairs from reference (preferred) vs.
    context-free generation (dispreferred), then applies a DPO-style
    preference loss combined with the standard cross-entropy objective.
    """

    def __init__(
        self,
        hidden_size: int = 1024,
        projection_dim: int = 128,
        temperature: float = 0.1,
        beta: float = 0.5,    # DPO β — controls preference strength
        alpha: float = 0.15,  # CPO weight in L_total
    ):
        super().__init__()
        self.projection_dim = projection_dim
        self.temperature = temperature
        self.beta = beta
        self.alpha = alpha

        self.projector = ResponseProjector(
            hidden_size=hidden_size,
            projection_dim=projection_dim,
        )

    def forward(
        self,
        pos_hidden_states: torch.Tensor,      # (B, T, D) — from reference summary
        neg_hidden_states: torch.Tensor,      # (B, T, D) — from context-free generation
        pos_labels: Optional[torch.Tensor] = None,  # reference labels (for CE loss)
        neg_labels: Optional[torch.Tensor] = None,  # context-free labels
    ) -> Tuple[torch.Tensor, Dict[str, float]]:
        """Compute the CPO loss.

        Returns:
          cpo_loss: scalar preference loss
          metrics:  dict with diagnostics
        """
        B = pos_hidden_states.shape[0]

        # Project hidden states to compact representations
        pos_proj = self.projector(pos_hidden_states)  # (B, proj_dim)
        neg_proj = self.projector(neg_hidden_states)  # (B, proj_dim)

        # ── DPO-style preference loss ──
        # log π_θ(y_w|x) ∝ -distance(pos_proj, anchor)^2 / τ
        # For simplicity, we use the projection norms as implicit scores
        # (higher norm = more confident = higher implicit reward)
        pos_score = pos_proj.norm(dim=-1) / self.temperature   # (B,)
        neg_score = neg_proj.norm(dim=-1) / self.temperature   # (B,)

        log_ratio = pos_score - neg_score                       # (B,)
        cpo_loss = -F.logsigmoid(self.beta * log_ratio).mean()

        # ── Auxiliary contrastive loss ──
        # Also push pos and neg apart in the projection space via a margin
        sim_matrix = torch.matmul(pos_proj, neg_proj.T)  # (B, B)
        contrastive_labels = torch.arange(B, device=pos_proj.device)
        contrastive_loss = F.cross_entropy(
            sim_matrix / self.temperature, contrastive_labels
        )

        # Combined
        total_cpo = cpo_loss + 0.1 * contrastive_loss

        # ── Diagnostics ──
        with torch.no_grad():
            pos_norm_mean = pos_score.mean().item()
            neg_norm_mean = neg_score.mean().item()
            margin = (pos_score - neg_score).mean().item()
            accuracy = (pos_score > neg_score).float().mean().item()

        metrics = {
            "cpo_loss": total_cpo.item(),
            "dpo_loss": cpo_loss.item(),
            "contrastive_loss": contrastive_loss.item(),
            "pos_score_mean": pos_norm_mean,
            "neg_score_mean": neg_norm_mean,
            "preference_margin": margin,
            "preference_accuracy": accuracy,
        }

        return total_cpo, metrics


# ═══════════════════════════════════════════════════════════════════════
# Context-free summary generator (for constructing dispreferred samples)
# ═══════════════════════════════════════════════════════════════════════


def generate_context_free_summary(
    model,
    tokenizer,
    num_tokens: int = 128,
    device: torch.device = None,
) -> torch.Tensor:
    """Generate a summary from the decoder alone (no encoder context).

    This represents what the model would produce if it hallucinated freely —
    used as the "dispreferred" response in CPO preference pairs.
    """
    if device is None:
        device = next(model.parameters()).device

    # Start with BOS token only
    bos_token_id = tokenizer.bos_token_id or tokenizer.cls_token_id or 0
    decoder_input_ids = torch.tensor([[bos_token_id]], device=device)

    # Get the underlying BART model
    if hasattr(model, 'bart'):
        bart = model.bart
    elif hasattr(model, 'model'):
        bart = model
    else:
        bart = model

    was_training = model.training
    model.eval()

    try:
        # Create a dummy encoder output: zero hidden states
        # This forces cross-attention to attend to nothing meaningful,
        # so the decoder relies entirely on its own language model prior
        hidden_size = bart.config.d_model
        dummy_encoder_hidden = torch.zeros(
            1, 1, hidden_size, device=device
        )
        from transformers.modeling_outputs import BaseModelOutput
        dummy_encoder_outputs = BaseModelOutput(
            last_hidden_state=dummy_encoder_hidden
        )

        with torch.no_grad():
            outputs = bart.generate(
                encoder_outputs=dummy_encoder_outputs,
                decoder_input_ids=decoder_input_ids,
                max_length=num_tokens,
                num_beams=1,
                do_sample=True,
                temperature=1.0,
                top_p=0.95,
                pad_token_id=tokenizer.pad_token_id or 0,
                eos_token_id=tokenizer.eos_token_id,
                use_cache=True,
            )
    except Exception:
        # Fallback: repeat BOS (should not happen with dummy encoder)
        with torch.no_grad():
            outputs = decoder_input_ids.repeat(1, num_tokens)
    finally:
        if was_training:
            model.train()

    return outputs
